{% set name = "wxutils" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03fba8348bf7f3a565c66d92bcbf54bdeab2f606947f0461b184ec45a0bb7c5d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - wxpython

test:
  requires:
    - python {{ python_min }}
  imports:
    - wxutils

about:
  home: https://github.com/newville/wxutils
  license: BSD
  license_file: LICENSE
  summary: Utilities and convenience classes and functions for wxPython

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
